### ISSUE TITLE
invalid bitdepth ? how to solve it?

### ISSUE THREAD

**Issue by leonbloy** [leonbloy/pngj#1]
_From [amoiz.sh...@gmail.com](https://code.google.com/u/105283883010898031340/) on August 29, 2010 06:46:39_

What steps will reproduce the problem? 1. add jars.
2. write a sample to genarate the png image follow the PngCreate class in the source jar.
3. run it. What is the expected output? What do you see instead? ar.com.hjg.pngj.PngjException: invalid bitdepth=5
	at ar.com.hjg.pngj.ImageInfo.<init>(ImageInfo.java:93)
	at ar.com.hjg.pngj.ImageInfo.<init>(ImageInfo.java:50)
	at cn.xiazhengxin.blog.util.GenPng.Create(GenPng.java:22)
……………… What version of the product are you using? On what operating system? JDK 6u21 on ubuntu 10.04 Please provide any additional information below. none.

_Original issue: http://code.google.com/p/pngj/issues/detail?id=1_

**Comment by leonbloy** [comment]
_From [hgonzalez@gmail.com](https://code.google.com/u/hgonzalez@gmail.com/) on May 25, 2011 10:10:29_

Apparently you are creating a file with a bitdepth=5? That is a invalid value, PNG only supports 1/4/8/16 -a and is library currently only supports RGB (8 or 16 bits)
